inherit_from:
- http://relaxed.ruby.style/rubocop.yml

Metrics/BlockLength:
  Enabled: false

Style/CaseIndentation:
  Enabled: false

Naming/ConstantName:
  Enabled: false

Lint/EndAlignment:
  Enabled: false

Lint/Eval:
  Enabled: false

Style/ExpandPathArguments:
  Enabled: false

Lint/InheritException:
  Enabled: false

Style/MethodCallWithoutArgsParentheses:
  Enabled: false

Style/RescueModifier:
  Enabled: false

Style/RescueStandardError:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Style/SpaceInsideBrackets:
  Enabled: false

Style/StderrPuts:
  Enabled: false

Layout/SpaceInsideStringInterpolation:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  Enabled: false

Style/YodaCondition:
  Enabled: false
