language: ruby
sudo: false

rvm:
- ruby-head
- 2.4.0
- 2.3.3
- 2.2
- 2.1
- 2.0
- 1.9.3
- jruby-9.1.7.0
- jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: 1.9.3

